# Generated by Django 4.2.7 on 2023-11-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_formpage_questions_alter_response_current_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='skip_calculation',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
