# Generated by Django 4.2.7 on 2023-11-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='form_page',
            field=models.ForeignKey(limit_choices_to={'assessment': models.F('assessment')}, on_delete=django.db.models.deletion.CASCADE, to='home.formpage'),
        ),
    ]
