# Generated by Django 4.2.7 on 2024-01-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_formpage_result_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='info',
            field=models.TextField(blank=True, help_text='Additional information about the question', null=True),
        ),
    ]
