# Generated by Django 4.2.7 on 2024-02-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_question_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='form_page',
        ),
        migrations.AddField(
            model_name='options',
            name='suggestions',
            field=models.ManyToManyField(blank=True, to='home.suggestion'),
        ),
    ]
