# Generated by Django 4.2.7 on 2024-02-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_category_caption_alter_category_title_and_more'),
        ('home', '0016_alter_category_caption_alter_category_title_and_more'),
    ]

    operations = [
    ]
