# Generated by Django 4.2.7 on 2024-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_formpage_page_number_options_question_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpage',
            options={'ordering': ['page_number']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_number']},
        ),
        migrations.RemoveField(
            model_name='options',
            name='question_number',
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(default=-1),
        ),
    ]
