# Generated by Django 4.2.7 on 2024-03-29 10:49

import django.contrib.postgres.fields
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_formpage_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='consents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='Comma seperated list of consents', max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='assessment',
            name='guidelines',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
